### ISSUE TITLE
An error occurs when I run scheduler.py: 'NoneType' object has no attribute 'request_func'

### ISSUE THREAD

**Issue by YJZyjz185672** [saantiaguilera/liquidity-sniper#2]
![image](https://user-images.githubusercontent.com/44958443/135227456-273e9f2a-2cc0-46ff-a253-bc7cd7eaaa6b.png)

**Comment by saantiaguilera** [comment]
Make sure to install the dependencies (brownie and others) through pip. I'm gonna be refactoring the py scripts in ts to reuse the package.json dependencies and avoid having multiple version managers, so you can wait until I've them :)
